const $ = (id) => document.getElementById(id);
const esc = (s) => String(s ?? '').replace(/[&<>"']/g, (c) => ({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
let endpoint;
async function request(path, body, token) {
  endpoint ??= fetch('./api.json', {cache:'no-cache'}).then(r => {if(!r.ok) throw Error();return r.json();}).then(({api}) => {const u=new URL(api);if(u.protocol!=='https:'||u.username||u.password)throw Error();return u.origin;}).catch(()=>'https://vercel-ia.onrender.com');
  const r = await fetch(`${await endpoint}/api/compte/${path}`, {method:body?'POST':'GET',headers:{...(body?{'Content-Type':'application/json'}:{}),...(token?{Authorization:`Bearer ${token}`}:{})},body:body?JSON.stringify(body):undefined,cache:'no-store',credentials:'omit',signal:AbortSignal.timeout(30000)});
  const data = await r.json().catch(()=>({error:'Réponse du serveur illisible.'}));
  if(!r.ok||data.error) { const e=Error(data.error||'Le serveur ne peut pas traiter la demande.');e.status=r.status;throw e; }return data;
}
export function initSupport(call=request) {
  const requestedApp = new URLSearchParams(location.search).get('app') === 'clips' ? 'clips' : 'launcher';
  $('reportForm').elements.app.value = requestedApp;
  let token=null,ticket=null,busy=false,capture=null,upload=0,uploading=false,listing=0,session=0;
  const errorText=e=>e.status?e.message:e.message==='Failed to fetch'||e.name==='TimeoutError'?'Serveur injoignable. Réessaie dans un instant.':e.message;
  const lock=(form,on)=>[...form.elements].forEach(el=>el.disabled=on);
  function resetLogin(){ticket=null;$('twoFactor').hidden=true;$('credentials').hidden=false;$('loginForm').elements.password.required=true;$('loginForm').elements.email.required=true;$('loginForm').elements.code.required=false;$('loginForm').elements.code.value='';}
  function clearCapture(){upload++;uploading=false;capture=null;$('captureFile').value='';$('capturePreview').removeAttribute('src');$('capturePreview').hidden=true;$('captureRemove').hidden=true;$('reportSubmit').disabled=busy;}
  function signedOut(){session++;listing++;token=null;resetLogin();clearCapture();$('workspace').hidden=true;$('loginPanel').hidden=false;$('ticketList').replaceChildren();$('accountName').textContent='';$('reportForm').reset();}
  async function list(){const generation=++listing;$('ticketList').textContent='Chargement…';try{const r=await call('support',null,token);if(generation!==listing)return;const labels={received:'Reçue',investigating:'En cours',resolved:'Résolue'};$('ticketList').innerHTML=r.tickets?.length?r.tickets.map(t=>`<article class="ticket"><span class="badge">${esc(labels[t.status]??t.status)}</span><h3>${esc(t.title)}</h3><time>${new Date(t.at).toLocaleDateString('fr-FR')}</time><p>${esc(t.description)}</p>${t.reply?`<blockquote><b>Réponse de l’équipe</b><br>${esc(t.reply)}</blockquote>`:'<p class="subtle">La réponse de l’équipe apparaîtra ici.</p>'}</article>`).join(''):'Aucune demande pour le moment.';}catch(e){if(generation!==listing)return;if(e.status===401){signedOut();$('loginStatus').textContent='Session expirée. Reconnecte-toi.';}else $('ticketList').textContent=errorText(e);}}
  $('loginForm').addEventListener('submit',async e=>{e.preventDefault();if(busy)return;busy=true;const f=e.currentTarget;lock(f,true);$('loginStatus').textContent='Connexion…';try{const r=await call(ticket?'connexion/2fa':'connexion',ticket?{ticket,code:f.elements.code.value}:{email:f.elements.email.value,motDePasse:f.elements.password.value});f.elements.password.value='';if(r.need2fa){ticket=r.ticket;$('credentials').hidden=true;$('twoFactor').hidden=false;f.elements.password.required=false;f.elements.email.required=false;f.elements.code.required=true;$('loginStatus').textContent='Saisis ton code pour terminer la connexion.';}else{if(!r.token)throw Error('Connexion incomplète. Réessaie.');token=r.token;session++;$('accountName').textContent=r.compte?.pseudo??'Compte History';$('loginPanel').hidden=true;$('workspace').hidden=false;$('loginStatus').textContent='';f.reset();resetLogin();await list();}}catch(err){$('loginStatus').textContent=errorText(err);}finally{busy=false;lock(f,false);if(ticket)f.elements.code.focus();}});
  $('backLogin').addEventListener('click',()=>{resetLogin();$('loginStatus').textContent='';});
  $('logout').addEventListener('click',async()=>{if(busy)return;const old=token;signedOut();try{await call('deconnexion',{},old);}catch{$('loginStatus').textContent='Déconnecté de cette page. La révocation côté serveur n’a pas pu être confirmée.';}});
  $('refresh').addEventListener('click',()=>{if(!busy)list();});
  async function pick(file){if(!file||busy)return;clearCapture();const generation=upload;uploading=true;$('reportSubmit').disabled=true;$('reportStatus').textContent='Préparation de la capture…';try{if(!['image/png','image/jpeg','image/webp'].includes(file.type)||file.size>10*1024*1024)throw Error('Choisis un PNG, JPG ou WebP de moins de 10 Mo.');const bitmap=await createImageBitmap(file);let data;try{const ratio=Math.min(1,1280/Math.max(bitmap.width,bitmap.height));const canvas=document.createElement('canvas');canvas.width=Math.max(1,Math.round(bitmap.width*ratio));canvas.height=Math.max(1,Math.round(bitmap.height*ratio));canvas.getContext('2d').drawImage(bitmap,0,0,canvas.width,canvas.height);for(const quality of [.82,.65,.45]){data=canvas.toDataURL('image/jpeg',quality);if(data.length<1800000)break;}}finally{bitmap.close();}if(generation!==upload)return;if(data.length>=1800000)throw Error('Image trop volumineuse. Choisis une capture plus petite.');capture=data;$('capturePreview').src=data;$('capturePreview').hidden=false;$('captureRemove').hidden=false;$('reportStatus').textContent='Capture prête : vérifie-la avant l’envoi.';}catch(e){if(generation===upload)$('reportStatus').textContent=errorText(e);}finally{if(generation===upload){uploading=false;$('reportSubmit').disabled=busy;}}}
  $('captureFile').addEventListener('change',e=>pick(e.target.files[0]));$('captureRemove').addEventListener('click',clearCapture);
  for(const type of ['dragover','drop'])$('captureDrop').addEventListener(type,e=>{e.preventDefault();if(type==='drop')pick(e.dataTransfer.files[0]);});
  $('reportForm').addEventListener('submit',async e=>{e.preventDefault();if(busy||uploading||!token)return;busy=true;const f=e.currentTarget,generation=session;const body={app:f.elements.app.value,title:f.elements.title.value,description:f.elements.description.value,img:capture};lock(f,true);$('logout').disabled=true;$('reportStatus').textContent='Envoi…';try{await call('support',body,token);if(generation!==session)return;f.reset();f.elements.app.value=requestedApp;clearCapture();$('reportStatus').textContent='Demande envoyée. Retrouve son suivi ci-dessous.';await list();}catch(err){$('reportStatus').textContent=errorText(err);}finally{busy=false;lock(f,false);$('logout').disabled=false;}});
  document.addEventListener('visibilitychange',()=>document.body.classList.toggle('paused',document.hidden));
}
if(document.body.dataset.support==='live')initSupport();
