import assert from 'node:assert/strict';
import { EventEmitter } from 'node:events';
import { nativeCaptureArgs, startNativeCapture } from '../src/nativeCapture.js';
const opts = {enc:'h264_nvenc',height:1080,fps:60,width:1920,sourceHeight:1080};
const args = nativeCaptureArgs(opts);
assert.ok(args.some(s => s.includes('ddagrab=output_idx=0:framerate=60')));
assert.ok(!args.some(s => s.includes('hwdownload')), 'NVIDIA taille native reste sur le GPU');
assert.ok(nativeCaptureArgs({...opts,enc:'h264_amf'}).some(s => s.includes('hwdownload')));
assert.throws(()=>nativeCaptureArgs({...opts,enc:'libx264'}));
assert.ok(nativeCaptureArgs({...opts,width:1280,sourceHeight:720,enc:'h264_amf'}).some(s => s.includes('scale=1280:720')), 'pas de faux 1080p par agrandissement');
const child = () => { const p = new EventEmitter();p.stdout=new EventEmitter();p.stderr=new EventEmitter();p.stdout.pause=()=>{};p.stdout.resume=()=>{};p.kill=()=>p.killed=true;return p; };
let p=child(), chunks=0, failures=0;
const capture=startNativeCapture('fake',opts,async()=>chunks++,()=>failures++,()=>p);
p.stdout.emit('data',Buffer.from('header'));await capture.ready;await new Promise(r=>setImmediate(r));
assert.equal(chunks,1);assert.ok(capture.startedAt>0);
p.emit('close',1);assert.equal(failures,1);assert.ok(p.killed);
p=child();const stopped=startNativeCapture('fake',opts,()=>{},()=>failures++,()=>p);
const rejected=assert.rejects(stopped.ready,/arrêtée/);stopped.stop();await rejected;p.emit('close',0);assert.equal(failures,1);
p=child();const failed=startNativeCapture('fake',opts,()=>{},()=>failures++,()=>p);
const unavailable=assert.rejects(failed.ready,/indisponible/);p.emit('error',Error('indisponible'));await unavailable;
console.log('✅ Native : source DDA, encodeur matériel, sans upscale, arrêt et erreur de démarrage');
