export function initQuickSupport(api, app) {
 const button=document.createElement('button');button.type='button';button.className='qs-trigger';button.title='Contacter le support';button.innerHTML='<span aria-hidden="true">✉</span> Support';document.querySelector('.top .winbtns').before(button);
 const dialog=document.createElement('dialog');dialog.className='qs-panel';dialog.setAttribute('aria-label','Support History');dialog.innerHTML=`<header><div><small>HISTORY / SUPPORT</small><h2>On t’écoute.</h2></div><button type="button" data-close aria-label="Fermer le support">×</button></header><nav><button type="button" data-tab="new">Écrire</button><button type="button" data-tab="list">Mes demandes</button></nav><form><label>Titre<input name="title" minlength="4" maxlength="100" required placeholder="Le problème en quelques mots"></label><label>Ton message<textarea name="description" minlength="10" maxlength="4000" rows="4" required placeholder="Que s’est-il passé ?"></textarea></label><label class="qs-drop">Capture facultative<input type="file" accept="image/png,image/jpeg,image/webp"><small>PNG, JPG, WebP · 10 Mo max.</small></label><img class="qs-preview" alt="Capture jointe" hidden><button type="button" data-remove hidden>Retirer la capture</button><p class="qs-hint">Demande privée. Retrouve la réponse ici ou sur le site avec le même compte History.</p><button class="qs-send">Envoyer ↗</button></form><div data-list hidden></div><p role="status"></p>`;document.body.append(dialog);
 const q=s=>dialog.querySelector(s),status=q('[role=status]');let busy=false,img=null,upload=0,uploading=false,generation=0;
 const check=r=>{if(!r||r.error)throw Error(r?.error||'Support indisponible. Réessaie.');return r;};
 const resetImage=()=>{upload++;uploading=false;img=null;q('input[type=file]').value='';q('img').hidden=true;q('img').removeAttribute('src');q('[data-remove]').hidden=true;q('.qs-send').disabled=busy;};
 const close=()=>{if(!busy)dialog.close();};q('[data-close]').onclick=close;dialog.addEventListener('cancel',e=>{if(busy)e.preventDefault();});dialog.addEventListener('close',()=>{generation++;upload++;uploading=false;q('.qs-send').disabled=false;});button.onclick=()=>{if(!dialog.open)dialog.showModal();};
 async function list(){const current=++generation;status.textContent='Chargement…';q('[data-list]').replaceChildren();try{const r=check(await api.supportList());if(current!==generation)return;const labels={received:'Reçue',investigating:'En cours',resolved:'Résolue'};for(const t of (r.tickets??[])){const article=document.createElement('article');const title=document.createElement('b');title.textContent=t.title;const state=document.createElement('small');state.textContent=t.app==='clips'?'Clips':'Launcher';const badge=document.createElement('span');badge.className='qs-badge';badge.dataset.status=t.status;badge.textContent=labels[t.status]??t.status;state.append(badge);const text=document.createElement('p');text.textContent=t.reply||'L’équipe répondra ici.';article.append(title,state,text);q('[data-list]').append(article);}status.textContent=r.tickets?.length?'':'Aucune demande pour le moment.';}catch(e){if(current===generation)status.textContent=e.message;}}
 for(const tab of dialog.querySelectorAll('[data-tab]'))tab.onclick=()=>{if(busy)return;const show=tab.dataset.tab==='new';q('form').hidden=!show;q('[data-list]').hidden=show;status.textContent='';generation++;if(!show)list();};
 q('[data-remove]').onclick=resetImage;
 async function pick(file){if(!file||busy)return;resetImage();const current=upload;uploading=true;q('.qs-send').disabled=true;try{if(!['image/png','image/jpeg','image/webp'].includes(file.type)||file.size>10485760)throw Error('Choisis une image PNG, JPG ou WebP de moins de 10 Mo.');const bitmap=await createImageBitmap(file);let data;try{const scale=Math.min(1,1280/Math.max(bitmap.width,bitmap.height));const canvas=document.createElement('canvas');canvas.width=Math.max(1,Math.round(bitmap.width*scale));canvas.height=Math.max(1,Math.round(bitmap.height*scale));canvas.getContext('2d').drawImage(bitmap,0,0,canvas.width,canvas.height);for(const quality of [.8,.6,.4]){data=canvas.toDataURL('image/jpeg',quality);if(data.length<1800000)break;}}finally{bitmap.close();}if(current!==upload)return;if(data.length>=1800000)throw Error('Image trop volumineuse.');img=data;q('img').src=img;q('img').hidden=false;q('[data-remove]').hidden=false;status.textContent='Capture prête. Vérifie les informations visibles avant l’envoi.';}catch(e){if(current===upload)status.textContent=e.message;}finally{if(current===upload){uploading=false;q('.qs-send').disabled=busy;}}}
 q('input[type=file]').onchange=e=>pick(e.target.files[0]);for(const type of ['dragover','drop'])q('.qs-drop').addEventListener(type,e=>{e.preventDefault();e.stopPropagation();if(type==='drop')pick(e.dataTransfer.files[0]);});
 q('form').onsubmit=async e=>{e.preventDefault();if(busy||uploading)return;busy=true;const form=e.currentTarget,body={...Object.fromEntries(new FormData(form)),img,app};for(const el of form.elements)el.disabled=true;status.textContent='Envoi…';try{check(await api.supportSend(body));form.reset();resetImage();status.textContent='Envoyé ! La réponse apparaîtra dans Mes demandes.';}catch(err){status.textContent=err.message;}finally{busy=false;for(const el of form.elements)el.disabled=false;}};
}
