// Pont minimal et sûr entre l'interface et Windows : seulement ces fonctions, rien d'autre.
const { contextBridge, ipcRenderer, webUtils } = require('electron');

contextBridge.exposeInMainWorld('launcher', {
  scan: () => ipcRenderer.invoke('lib:scan'),
  action: (id, action) => ipcRenderer.invoke('item:action', id, action),
  setItem: (id, patch) => ipcRenderer.invoke('item:set', id, patch),
  settings: () => ipcRenderer.invoke('settings:get'),
  setSettings: (patch) => ipcRenderer.invoke('settings:set', patch),
  win: (what) => ipcRenderer.send('win', what),
  onActive: (fn) => ipcRenderer.on('lib:active', (_e, ids) => fn(ids)),
  onUpdate: (fn) => ipcRenderer.on('lib:update', (_e, lib) => fn(lib)),
  details: (id) => ipcRenderer.invoke('item:details', id),
  openLink: (which) => ipcRenderer.invoke('open:link', which),
  reco: () => ipcRenderer.invoke('reco:get'),
  openReco: (steamId) => ipcRenderer.invoke('reco:open', steamId),
  freeGames: () => ipcRenderer.invoke('free:get'),
  friends: (force) => ipcRenderer.invoke('friends:get', Boolean(force)),
  friendAction: (action, id64) => ipcRenderer.invoke('friends:open', action, id64),
  deals: () => ipcRenderer.invoke('deals:get'),
  openDeal: (appid) => ipcRenderer.invoke('deals:open', appid),
  rescan: () => ipcRenderer.invoke('lib:scan'),
  boost: () => ipcRenderer.invoke('boost:get'),
  setBoost: (patch) => ipcRenderer.invoke('boost:set', patch),
  pc: () => ipcRenderer.invoke('pc:snapshot'),
  cleanScan: () => ipcRenderer.invoke('clean:scan'),
  cleanRun: (ids) => ipcRenderer.invoke('clean:run', ids),
  hFriends: () => ipcRenderer.invoke('hfriends:get'),
  hFriendAdd: (code) => ipcRenderer.invoke('hfriends:add', code),
  hFriendAccept: (id) => ipcRenderer.invoke('hfriends:accept', id),
  hFriendRemove: (id) => ipcRenderer.invoke('hfriends:remove', id),
  events: () => ipcRenderer.invoke('events:get'),
  eventCreate: (e) => ipcRenderer.invoke('events:create', e),
  eventRespond: (id, r) => ipcRenderer.invoke('events:respond', id, r),
  eventCancel: (id) => ipcRenderer.invoke('events:cancel', id),
  captures: (id) => ipcRenderer.invoke('captures:get', id),
  openCapture: (token) => ipcRenderer.invoke('captures:open', token),
  captureFolder: (token) => ipcRenderer.invoke('captures:folder', token),
  achievements: (id) => ipcRenderer.invoke('ach:get', id),
  timeToBeat: (id) => ipcRenderer.invoke('hltb:get', id),
  collections: () => ipcRenderer.invoke('col:get'),
  saveCollections: (c) => ipcRenderer.invoke('col:save', c),
  addGameFile: (file) => ipcRenderer.invoke('custom:add', webUtils.getPathForFile(file)),
  pickGame: () => ipcRenderer.invoke('custom:pick'),
  renameGame: (id, name) => ipcRenderer.invoke('custom:rename', id, name),
  removeGame: (id) => ipcRenderer.invoke('custom:remove', id),
  optiScan: () => ipcRenderer.invoke('opti:scan'),
  optiRun: (plan) => ipcRenderer.invoke('opti:run', plan),
  optiStartup: (name, on) => ipcRenderer.invoke('opti:startup', name, on),
  optiTweak: (id, on) => ipcRenderer.invoke('opti:tweak', id, on),
  optiDeep: () => ipcRenderer.invoke('opti:deep'),
  recap: () => ipcRenderer.invoke('recap:get'),
  news: () => ipcRenderer.invoke('news:get'),
  gameNews: (id) => ipcRenderer.invoke('news:game', id),
  openNews: (appid, gid) => ipcRenderer.invoke('news:open', appid, gid),
  colorOf: (id) => ipcRenderer.invoke('color:of', id),
  onAsk: (fn) => ipcRenderer.on('ui:ask', (_e, q) => fn(q)),
  answer: (id, ok) => ipcRenderer.send('ui:answer', id, Boolean(ok)),
  onOpti: (fn) => ipcRenderer.on('opti:progress', (_e, p) => fn(p)),
  optiAuto: (on) => ipcRenderer.invoke('opti:auto', on),
  cachedLibrary: () => ipcRenderer.invoke('lib:cached'),
  onPalette: (fn) => ipcRenderer.on('palette:open', () => fn()),
  fullscreen: (on) => ipcRenderer.invoke('win:fullscreen', on),
  fivemJoin: (code) => ipcRenderer.invoke('fivem:join', code),
  callStart: (fid) => ipcRenderer.invoke('call:start', fid),
  callAnswer: (id, oui) => ipcRenderer.invoke('call:answer', id, oui),
  callSignal: (id, data) => ipcRenderer.invoke('call:signal', id, data),
  callPoll: (id, after) => ipcRenderer.invoke('call:poll', id, after),
  callEnd: (id) => ipcRenderer.invoke('call:end', id),
  onIncomingCall: (fn) => ipcRenderer.on('call:incoming', (_e, d) => fn(d)),
  chatThread: (fid) => ipcRenderer.invoke('chat:thread', fid),
  chatSend: (fid, text) => ipcRenderer.invoke('chat:send', fid, text),
  friendInvite: (fid, type) => ipcRenderer.invoke('friend:invite', fid, type),
  friendJoin: (fid) => ipcRenderer.invoke('friend:join', fid),
  onSocial: (fn) => ipcRenderer.on('social:live', (_e, d) => fn(d)),
  onChatOpen: (fn) => ipcRenderer.on('chat:open', (_e, d) => fn(d)),
  backupInfo: () => ipcRenderer.invoke('backup:get'),
  backupNow: () => ipcRenderer.invoke('backup:now'),
  backupRestore: () => ipcRenderer.invoke('backup:restore'),
  pcDiag: (force) => ipcRenderer.invoke('pc:diag', Boolean(force)),
  pcProcs: () => ipcRenderer.invoke('pc:procs'),
  pcKill: (pid, p) => ipcRenderer.invoke('pc:kill', pid, p),
  pcDefScan: (type) => ipcRenderer.invoke('pc:defscan', type),
  pcDefRemove: () => ipcRenderer.invoke('pc:defremove'),
  pcBench: () => ipcRenderer.invoke('pc:bench'),
  pcBenchHistory: () => ipcRenderer.invoke('pc:benchHistory'),
  pcReport: () => ipcRenderer.invoke('pc:report'),
  pcDeep: () => ipcRenderer.invoke('pc:deep'),
  health: (refresh) => ipcRenderer.invoke('health:get', refresh),
  scanStart: () => ipcRenderer.invoke('scan:start'),
  scanStop: () => ipcRenderer.invoke('scan:stop'),
  demo: () => ipcRenderer.invoke('demo:get'),
  tools: (id) => ipcRenderer.invoke('tools:get', id),
  toolsProfile: (id, patch) => ipcRenderer.invoke('tools:profile', id, patch),
  savesBackup: (id) => ipcRenderer.invoke('saves:backup', id),
  savesRestore: (id, bid) => ipcRenderer.invoke('saves:restore', id, bid),
  savesPick: (id) => ipcRenderer.invoke('saves:pick', id),
  savesOpen: () => ipcRenderer.invoke('saves:open'),
  shadersClear: (id, which) => ipcRenderer.invoke('shaders:clear', id, which),
  steamMove: (id, lib) => ipcRenderer.invoke('steam:move', id, lib),
  onMove: (fn) => ipcRenderer.on('move:progress', (_e, p) => fn(p)),
  priceSearch: (q) => ipcRenderer.invoke('price:search', q),
  priceList: () => ipcRenderer.invoke('price:list'),
  priceSet: (appId, name, target) => ipcRenderer.invoke('price:set', appId, name, target),
  fpsEnable: () => ipcRenderer.invoke('fps:enable'),
  fpsDisable: () => ipcRenderer.invoke('fps:disable'),
  benchQuick: () => ipcRenderer.invoke('bench:quick'),
  settingsHistory: () => ipcRenderer.invoke('settingsHistory:get'),
  settingsRestore: (at) => ipcRenderer.invoke('settingsHistory:restore', at),
  driverOpen: (which) => ipcRenderer.invoke('pc:driverOpen', which),
  driverInfo: () => ipcRenderer.invoke('pc:driver'),
  onSettingsChanged: (fn) => ipcRenderer.on('settings:changed', (_e, s) => fn(s)),
  scanLast: () => ipcRenderer.invoke('scan:last'),
  scanShow: (p) => ipcRenderer.invoke('scan:show', p),
  scanTrash: (paths) => ipcRenderer.invoke('scan:trash', paths),
  scanClean: (kinds) => ipcRenderer.invoke('scan:clean', kinds),
  onScan: (fn) => ipcRenderer.on('scan:progress', (_e, p) => fn(p)),
  wuSearch: () => ipcRenderer.invoke('wu:search'),
  wuInstall: (ids) => ipcRenderer.invoke('wu:install', ids),
  wuReboot: () => ipcRenderer.invoke('wu:reboot'),
  onWu: (fn) => ipcRenderer.on('wu:progress', (_e, p) => fn(p)),
  optiSys: () => ipcRenderer.invoke('opti:sys'),
  optiSysApply: (changes) => ipcRenderer.invoke('opti:sysApply', changes),
  optiStorage: () => ipcRenderer.invoke('opti:storage'),
  optiRepair: () => ipcRenderer.invoke('opti:repair'),
  onRepair: (fn) => ipcRenderer.on('opti:repairProgress', (_e, p) => fn(p)),
  onPcProgress: (fn) => ipcRenderer.on('pc:progress', (_e, p) => fn(p)),
  gmodAddons: () => ipcRenderer.invoke('gmod:addons'),
  gmodDetails: (x) => ipcRenderer.invoke('gmod:details', x),
  gmodInstall: (id) => ipcRenderer.invoke('gmod:install', id),
  gmodBrowse: () => ipcRenderer.invoke('gmod:browse'),
  progress: () => ipcRenderer.invoke('progress:get'),
  netPing: () => ipcRenderer.invoke('net:ping'),
  netDns: () => ipcRenderer.invoke('net:dns'),
  restorePoint: () => ipcRenderer.invoke('pc:restorepoint'),
  gameReqs: (id) => ipcRenderer.invoke('game:reqs', id),
  gameTips: (id) => ipcRenderer.invoke('ai:gametips', id),
  pcPdf: (title, body) => ipcRenderer.invoke('pc:pdf', title, body),
  libExport: () => ipcRenderer.invoke('lib:export'),
  libImport: () => ipcRenderer.invoke('lib:import'),
  benchRanking: () => ipcRenderer.invoke('bench:ranking'),
  pcTemps: () => ipcRenderer.invoke('pc:temps'),
  onInvite: (fn) => ipcRenderer.on('invite:friend', (_e, d) => fn(d)),
  fivemServers: () => ipcRenderer.invoke('fivem:servers'),
  fivemFav: (code, on) => ipcRenderer.invoke('fivem:fav', code, Boolean(on)),
  gameHistory: (id) => ipcRenderer.invoke('stats:game', id),
  onAppUpdate: (fn) => ipcRenderer.on('update:state', (_e, u) => fn(u)),
  updateInfo: () => ipcRenderer.invoke('update:get'),
  installUpdate: () => ipcRenderer.invoke('update:install'),
  checkUpdate: (now) => ipcRenderer.invoke('update:check', Boolean(now)),
  downloadUpdate: (now) => ipcRenderer.invoke('update:download', Boolean(now)),
  version: () => ipcRenderer.invoke('app:version'),
  onCols: (fn) => ipcRenderer.on('cols:update', (_e, c) => fn(c)),
  onAppError: (fn) => ipcRenderer.on('app:error', (_e, m) => fn(m)),
  onOverlay: (fn) => ipcRenderer.on('overlay:data', (_e, d) => fn(d)),
  openFree: (slug) => ipcRenderer.invoke('free:open', slug),
  stats: (period) => ipcRenderer.invoke('stats:get', period),
  nowPlaying: () => ipcRenderer.invoke('media:now'),
  mediaKey: (name) => ipcRenderer.invoke('media:key', name),
  ask: (message) => ipcRenderer.invoke('ai:ask', message),
  setVoice: (on) => ipcRenderer.invoke('voice:set', on),
  transcribe: (audio, mime) => ipcRenderer.invoke('voice:transcribe', audio, mime),
  onVoice: (fn) => { ipcRenderer.on('voice:state', (_e, v) => fn('state', v)); ipcRenderer.on('voice:heard', (_e, v) => fn('heard', v)); ipcRenderer.on('voice:reply', (_e, v) => fn('reply', v)); ipcRenderer.on('voice:record', (_e, v) => fn('record', v)); },
  account: () => ipcRenderer.invoke('account:get'),
  unlock2fa: (code) => ipcRenderer.invoke('account:unlock', code),
  discordCode: () => ipcRenderer.invoke('account:discordCode'),
  discordUnlink: () => ipcRenderer.invoke('account:discordUnlink'),
  groupCreate: (nom, membres) => ipcRenderer.invoke('groups:create', nom, membres),
  groupNotify: (id, text) => ipcRenderer.invoke('groups:notify', id, text),
  groupLeave: (id) => ipcRenderer.invoke('groups:leave', id),
  platformAccounts: () => ipcRenderer.invoke('accounts:get'),
  setPlatformAccounts: (patch) => ipcRenderer.invoke('accounts:set', patch),
  verify: (id) => ipcRenderer.invoke('verify:start', id),
  cancelVerify: () => ipcRenderer.invoke('verify:cancel'),
  repair: (id) => ipcRenderer.invoke('verify:repair', id),
  onVerify: (fn) => ipcRenderer.on('verify:progress', (_e, p) => fn(p)),
  register: (body) => ipcRenderer.invoke('account:inscription', body),
  login: (body) => ipcRenderer.invoke('account:connexion', body),
  login2fa: (ticket, code) => ipcRenderer.invoke('account:2fa', ticket, code),
  verifyEmail: (code) => ipcRenderer.invoke('account:verif', code),
  verifyResend: () => ipcRenderer.invoke('account:verifResend'),
  forgotPassword: (email) => ipcRenderer.invoke('account:forgot', email),
  resetPassword: (email, code, pw) => ipcRenderer.invoke('account:reset', email, code, pw),
  twoFaStart: () => ipcRenderer.invoke('account:2faStart'),
  twoFaOn: (code) => ipcRenderer.invoke('account:2faOn', code),
  twoFaOff: (pw, code) => ipcRenderer.invoke('account:2faOff', pw, code),
  logout: () => ipcRenderer.invoke('account:logout'),
  skipAccount: () => ipcRenderer.invoke('account:skip'),
});
