// Pont minimal et sûr entre l'interface et Windows : seulement ces fonctions, rien d'autre.
const { contextBridge, ipcRenderer } = require('electron');

contextBridge.exposeInMainWorld('launcher', {
  scan: () => ipcRenderer.invoke('lib:scan'),
  action: (id, action) => ipcRenderer.invoke('item:action', id, action),
  setItem: (id, patch) => ipcRenderer.invoke('item:set', id, patch),
  settings: () => ipcRenderer.invoke('settings:get'),
  setSettings: (patch) => ipcRenderer.invoke('settings:set', patch),
  win: (what) => ipcRenderer.send('win', what),
  onActive: (fn) => ipcRenderer.on('lib:active', (_e, ids) => fn(ids)),
  onUpdate: (fn) => ipcRenderer.on('lib:update', (_e, lib) => fn(lib)),
  details: (id) => ipcRenderer.invoke('item:details', id),
  openLink: (which) => ipcRenderer.invoke('open:link', which),
  reco: () => ipcRenderer.invoke('reco:get'),
  openReco: (steamId) => ipcRenderer.invoke('reco:open', steamId),
  freeGames: () => ipcRenderer.invoke('free:get'),
  friends: (force) => ipcRenderer.invoke('friends:get', Boolean(force)),
  friendAction: (action, id64) => ipcRenderer.invoke('friends:open', action, id64),
  deals: () => ipcRenderer.invoke('deals:get'),
  openDeal: (appid) => ipcRenderer.invoke('deals:open', appid),
  rescan: () => ipcRenderer.invoke('lib:scan'),
  openFree: (slug) => ipcRenderer.invoke('free:open', slug),
  stats: (period) => ipcRenderer.invoke('stats:get', period),
  nowPlaying: () => ipcRenderer.invoke('media:now'),
  mediaKey: (name) => ipcRenderer.invoke('media:key', name),
  ask: (message) => ipcRenderer.invoke('ai:ask', message),
  setVoice: (on) => ipcRenderer.invoke('voice:set', on),
  transcribe: (audio, mime) => ipcRenderer.invoke('voice:transcribe', audio, mime),
  onVoice: (fn) => { ipcRenderer.on('voice:state', (_e, v) => fn('state', v)); ipcRenderer.on('voice:heard', (_e, v) => fn('heard', v)); ipcRenderer.on('voice:reply', (_e, v) => fn('reply', v)); },
  account: () => ipcRenderer.invoke('account:get'),
  platformAccounts: () => ipcRenderer.invoke('accounts:get'),
  setPlatformAccounts: (patch) => ipcRenderer.invoke('accounts:set', patch),
  verify: (id) => ipcRenderer.invoke('verify:start', id),
  cancelVerify: () => ipcRenderer.invoke('verify:cancel'),
  repair: (id) => ipcRenderer.invoke('verify:repair', id),
  onVerify: (fn) => ipcRenderer.on('verify:progress', (_e, p) => fn(p)),
  register: (body) => ipcRenderer.invoke('account:inscription', body),
  login: (body) => ipcRenderer.invoke('account:connexion', body),
  logout: () => ipcRenderer.invoke('account:logout'),
  skipAccount: () => ipcRenderer.invoke('account:skip'),
});
