// Pont minimal et sûr entre l'interface et Windows : seulement ces fonctions, rien d'autre.
const { contextBridge, ipcRenderer, webUtils } = require('electron');

contextBridge.exposeInMainWorld('launcher', {
  scan: () => ipcRenderer.invoke('lib:scan'),
  action: (id, action) => ipcRenderer.invoke('item:action', id, action),
  setItem: (id, patch) => ipcRenderer.invoke('item:set', id, patch),
  settings: () => ipcRenderer.invoke('settings:get'),
  setSettings: (patch) => ipcRenderer.invoke('settings:set', patch),
  win: (what) => ipcRenderer.send('win', what),
  onActive: (fn) => ipcRenderer.on('lib:active', (_e, ids) => fn(ids)),
  onUpdate: (fn) => ipcRenderer.on('lib:update', (_e, lib) => fn(lib)),
  details: (id) => ipcRenderer.invoke('item:details', id),
  openLink: (which) => ipcRenderer.invoke('open:link', which),
  reco: () => ipcRenderer.invoke('reco:get'),
  openReco: (steamId) => ipcRenderer.invoke('reco:open', steamId),
  freeGames: () => ipcRenderer.invoke('free:get'),
  friends: (force) => ipcRenderer.invoke('friends:get', Boolean(force)),
  friendAction: (action, id64) => ipcRenderer.invoke('friends:open', action, id64),
  deals: () => ipcRenderer.invoke('deals:get'),
  openDeal: (appid) => ipcRenderer.invoke('deals:open', appid),
  rescan: () => ipcRenderer.invoke('lib:scan'),
  boost: () => ipcRenderer.invoke('boost:get'),
  setBoost: (patch) => ipcRenderer.invoke('boost:set', patch),
  pc: () => ipcRenderer.invoke('pc:snapshot'),
  cleanScan: () => ipcRenderer.invoke('clean:scan'),
  cleanRun: (ids) => ipcRenderer.invoke('clean:run', ids),
  hFriends: () => ipcRenderer.invoke('hfriends:get'),
  hFriendAdd: (code) => ipcRenderer.invoke('hfriends:add', code),
  hFriendAccept: (id) => ipcRenderer.invoke('hfriends:accept', id),
  hFriendRemove: (id) => ipcRenderer.invoke('hfriends:remove', id),
  events: () => ipcRenderer.invoke('events:get'),
  eventCreate: (e) => ipcRenderer.invoke('events:create', e),
  eventRespond: (id, r) => ipcRenderer.invoke('events:respond', id, r),
  eventCancel: (id) => ipcRenderer.invoke('events:cancel', id),
  captures: (id) => ipcRenderer.invoke('captures:get', id),
  openCapture: (token) => ipcRenderer.invoke('captures:open', token),
  captureFolder: (token) => ipcRenderer.invoke('captures:folder', token),
  achievements: (id) => ipcRenderer.invoke('ach:get', id),
  timeToBeat: (id) => ipcRenderer.invoke('hltb:get', id),
  collections: () => ipcRenderer.invoke('col:get'),
  saveCollections: (c) => ipcRenderer.invoke('col:save', c),
  addGameFile: (file) => ipcRenderer.invoke('custom:add', webUtils.getPathForFile(file)),
  pickGame: () => ipcRenderer.invoke('custom:pick'),
  renameGame: (id, name) => ipcRenderer.invoke('custom:rename', id, name),
  removeGame: (id) => ipcRenderer.invoke('custom:remove', id),
  optiScan: () => ipcRenderer.invoke('opti:scan'),
  optiRun: (plan) => ipcRenderer.invoke('opti:run', plan),
  optiStartup: (name, on) => ipcRenderer.invoke('opti:startup', name, on),
  optiTweak: (id, on) => ipcRenderer.invoke('opti:tweak', id, on),
  optiDeep: () => ipcRenderer.invoke('opti:deep'),
  recap: () => ipcRenderer.invoke('recap:get'),
  news: () => ipcRenderer.invoke('news:get'),
  gameNews: (id) => ipcRenderer.invoke('news:game', id),
  openNews: (appid, gid) => ipcRenderer.invoke('news:open', appid, gid),
  colorOf: (id) => ipcRenderer.invoke('color:of', id),
  onAsk: (fn) => ipcRenderer.on('ui:ask', (_e, q) => fn(q)),
  answer: (id, ok) => ipcRenderer.send('ui:answer', id, Boolean(ok)),
  onOpti: (fn) => ipcRenderer.on('opti:progress', (_e, p) => fn(p)),
  optiAuto: (on) => ipcRenderer.invoke('opti:auto', on),
  cachedLibrary: () => ipcRenderer.invoke('lib:cached'),
  onPalette: (fn) => ipcRenderer.on('palette:open', () => fn()),
  fullscreen: (on) => ipcRenderer.invoke('win:fullscreen', on),
  onOverlay: (fn) => ipcRenderer.on('overlay:data', (_e, d) => fn(d)),
  openFree: (slug) => ipcRenderer.invoke('free:open', slug),
  stats: (period) => ipcRenderer.invoke('stats:get', period),
  nowPlaying: () => ipcRenderer.invoke('media:now'),
  mediaKey: (name) => ipcRenderer.invoke('media:key', name),
  ask: (message) => ipcRenderer.invoke('ai:ask', message),
  setVoice: (on) => ipcRenderer.invoke('voice:set', on),
  transcribe: (audio, mime) => ipcRenderer.invoke('voice:transcribe', audio, mime),
  onVoice: (fn) => { ipcRenderer.on('voice:state', (_e, v) => fn('state', v)); ipcRenderer.on('voice:heard', (_e, v) => fn('heard', v)); ipcRenderer.on('voice:reply', (_e, v) => fn('reply', v)); ipcRenderer.on('voice:record', (_e, v) => fn('record', v)); },
  account: () => ipcRenderer.invoke('account:get'),
  platformAccounts: () => ipcRenderer.invoke('accounts:get'),
  setPlatformAccounts: (patch) => ipcRenderer.invoke('accounts:set', patch),
  verify: (id) => ipcRenderer.invoke('verify:start', id),
  cancelVerify: () => ipcRenderer.invoke('verify:cancel'),
  repair: (id) => ipcRenderer.invoke('verify:repair', id),
  onVerify: (fn) => ipcRenderer.on('verify:progress', (_e, p) => fn(p)),
  register: (body) => ipcRenderer.invoke('account:inscription', body),
  login: (body) => ipcRenderer.invoke('account:connexion', body),
  logout: () => ipcRenderer.invoke('account:logout'),
  skipAccount: () => ipcRenderer.invoke('account:skip'),
});
