(() => {
 const $=id=>document.getElementById(id);let tickets=[];
 const labels={received:'Reçue',investigating:'En cours',resolved:'Résolue'};
 function h(tag,text,cls){const e=document.createElement(tag);if(text)e.textContent=text;if(cls)e.className=cls;return e;}
 async function api(path,body){const r=await fetch('/apps-admin/api/'+path,{method:body?'POST':'GET',headers:body?{'Content-Type':'application/json','X-Dashboard':'1'}:{},body:body?JSON.stringify(body):undefined});const d=await r.json();if(!r.ok){if(r.status===401)show(false);throw Error(d.error||'Serveur indisponible.');}return d;}
 function show(on){$('auth').hidden=on;$('desk').hidden=!on;$('logout').hidden=!on;if(!on){tickets=[];$('tickets').replaceChildren();}}
 function render(){const list=tickets.filter(t=>($('app').value==='all'||(t.app??'launcher')===$('app').value)&&($('status').value==='all'||t.status===$('status').value)&&`${t.name} ${t.title} ${t.description}`.toLowerCase().includes($('search').value.toLowerCase()));$('counts').replaceChildren(...Object.entries(labels).map(([key,label])=>h('span',`${tickets.filter(t=>t.status===key).length} ${label.toLowerCase()}${tickets.filter(t=>t.status===key).length>1?'s':''}`)));$('tickets').replaceChildren();if(!list.length)$('tickets').append(h('p','Aucune demande correspondante.'));
 for(const t of list){const card=h('article',null,'card'),who=h('div',null,'who');const av=t.avatar?h('img',null,'avatar'):h('span',(t.name||'?')[0],'avatar');if(t.avatar){av.src=t.avatar;av.alt='Photo de '+t.name;av.referrerPolicy='no-referrer';}const title=h('div');title.append(h('h2',t.title),h('small',`${t.displayName||t.name} · ${t.app==='clips'?'History Clips':'History Launcher'} · ${new Date(t.at).toLocaleString('fr-FR')}`));who.append(av,title,h('span',labels[t.status],'badge'));card.append(who,h('p',t.description,'message'),h('p',t.discordId?'Compte Discord lié':'Compte History','fine'));
 const diagnostic=h('details');diagnostic.append(h('summary','Diagnostic joint'),h('pre',Object.entries(t.diagnostic??{}).map(([k,v])=>`${k} : ${v}`).join('\n')||'Aucun diagnostic.'));card.append(diagnostic);
 const feedback=h('p');feedback.setAttribute('role','status');if(t.hasImage){const capture=h('button','Voir la capture');capture.onclick=async()=>{capture.disabled=true;try{const d=await api('launcher-support?id='+encodeURIComponent(t.id));if(d.ticket?.img){const img=h('img',null,'capture');img.src=d.ticket.img;img.alt='Capture jointe à la demande';capture.replaceWith(img);}}catch(e){feedback.textContent=e.message;capture.disabled=false;}};card.append(capture);}
 const reply=h('textarea');reply.rows=3;reply.maxLength=2000;reply.value=t.reply??'';reply.setAttribute('aria-label','Réponse à '+t.name);const status=h('select');status.setAttribute('aria-label','Statut');for(const [v,l]of Object.entries(labels)){const o=h('option',l);o.value=v;status.append(o);}status.value=t.status;const save=h('button','Envoyer la réponse');save.onclick=async()=>{save.disabled=true;try{await api('launcher-support',{id:t.id,status:status.value,reply:reply.value});t.reply=reply.value;t.status=status.value;feedback.textContent='Enregistré. Synchronisation Discord en cours.';}catch(e){feedback.textContent=e.message;}finally{save.disabled=false;}};const row=h('div',null,'row');row.append(status,save);card.append(reply,row,feedback);$('tickets').append(card);}}
 async function refresh(){try{$('notice').textContent='Chargement…';tickets=(await api('launcher-support')).tickets;render();$('notice').textContent='Les demandes et réponses sont partagées avec Discord, Launcher et Clips.';}catch(e){$('notice').textContent=e.message;}}
 $('login').onsubmit=async e=>{e.preventDefault();const b=e.currentTarget.querySelector('button');b.disabled=true;try{$('authStatus').textContent=(await api('lien',{discordId:$('discordId').value,apps:true})).message;}catch(e){$('authStatus').textContent=e.message;}finally{b.disabled=false;}};
 const token=location.pathname.endsWith('/connexion')?location.hash.slice(1):'';if(token){history.replaceState(null,'','/apps-admin/connexion');$('consume').hidden=false;$('login').hidden=true;$('consume').onclick=async()=>{$('consume').disabled=true;try{await api('login',{jeton:token});history.replaceState(null,'','/apps-admin');show(true);await refresh();}catch(e){$('authStatus').textContent=e.message;$('login').hidden=false;}finally{$('consume').disabled=false;}};}
 $('logout').onclick=async()=>{try{await api('logout',{});show(false);}catch(e){$('notice').textContent=e.message;}};$('refresh').onclick=refresh;for(const id of ['app','status','search'])$(id).addEventListener('input',render);api('moi').then(d=>{if(d.connecte){show(true);refresh();}}).catch(e=>{$('authStatus').textContent=e.message;});
})();
