import assert from 'node:assert/strict';
import { ocPlan } from '../src/core/oc.js';
assert.equal(ocPlan({ cpu: 'Intel Core i5-13600K', board: 'ASUS ROG STRIX Z790-F' }).cpuOc, 'oui');
assert.equal(ocPlan({ cpu: 'Intel Core i5-13600KF', board: 'MSI PRO B760M-A' }).cpuOc, 'limité');
assert.equal(ocPlan({ cpu: 'Intel Core i5-12400F', board: 'MSI PRO B660M' }).cpuOc, 'non');
assert.equal(ocPlan({ cpu: 'AMD Ryzen 7 7800X3D 8-Core Processor' }).cpuOc, 'limité');
assert.equal(ocPlan({ cpu: 'AMD Ryzen 5 5600X', board: 'Gigabyte B550 AORUS' }).cpuOc, 'oui');
const r = ocPlan({ cpu: 'AMD Ryzen 5 7600', ram: [{ speed: 6000, configured: 4800, type: 'DDR5' }] });
assert.equal(r.ramNow, 4800); assert.equal(r.ramSticks, 1); assert.match(r.ramHow[0], /EXPO.*4800.*6000/); assert.equal(r.ramLimited, false);
assert.equal(ocPlan({ cpu: 'x', ram: [{ speed: 3200, configured: 3200 }, { speed: 3200, configured: 3200 }] }).ramLimited, true);
console.log('oc ok');
const { parseRam, ocAdvice } = await import('../src/core/oc.js');
assert.deepEqual(parseRam('2x8 Go DDR4 3200').length, 2); assert.equal(parseRam('16 Go DDR5 6000 une barrette').length, 1); assert.equal(parseRam('16 Go')[0], undefined);
const k = ocPlan({ cpu: 'Intel Core i7-13700K', board: 'ASUS TUF Z790' });
assert.equal(ocAdvice(k, { cooling: 'AIO 360 mm' }).cpu, 'recommandé');
assert.equal(ocAdvice(k, { cooling: 'ventirad d’origine' }).cpu, 'BIOS seulement');
assert.equal(ocAdvice(k, { laptop: true }).cpu, 'déconseillé');
assert.equal(ocAdvice(k, { cooling: 'AIO', cpuTempMax: 92 }).cpu, 'déconseillé');
console.log('oc advice ok');
const { biosLink } = await import('../src/core/oc.js');
assert.equal(biosLink('Micro-Star International Co., Ltd. MAG B650 TOMAHAWK WIFI (MS-7D75)'), 'https://www.msi.com/Motherboard/MAG-B650-TOMAHAWK-WIFI/support#bios');
assert.equal(biosLink('ASUSTeK COMPUTER INC. TUF GAMING B550-PLUS'), 'https://www.asus.com/supportonly/TUF%20GAMING%20B550-PLUS/helpdesk_bios/');
assert.match(biosLink('ASRock B650M Pro RS', 'AMD Ryzen 5'), /asrock\.com\/mb\/AMD\/B650M%20Pro%20RS\/index\.asp#BIOS/);
assert.match(biosLink('Gigabyte Technology Co., Ltd. B550 AORUS ELITE V2'), /gigabyte\.com\/fr\/Search\?kw=B550%20AORUS%20ELITE%20V2/);
console.log('bios link ok');
const { personalPlan } = await import('../src/core/oc.js');
const ids = (s) => personalPlan(s).map((x) => x.id);
const k2 = { cpu: 'Intel Core i7-13700K', board: 'ASUS TUF Z790', cooling: 'AIO 360' };
assert.ok(ids({ ...k2, games: 'Valorant', need: 'max de fps en 240 Hz' }).includes('cpu_oc'), 'OC proposé si jeux CPU');
assert.ok(!ids({ ...k2, games: 'Cyberpunk', need: 'beaux graphismes' }).includes('cpu_oc'), 'pas d’OC si jeux GPU');
assert.ok(personalPlan({ ...k2, games: 'Valorant' }).find((x) => x.id === 'cpu_oc').optin);
assert.ok(ids({ cpu: 'i5-12400F', laptop: true, need: 'mon pc rame' }).includes('portable') && ids({ cpu: 'i5', laptop: true, need: 'mon pc rame' }).includes('format'));
assert.equal(ids({ cpu: 'x', cpuTempMax: 92 })[0], 'refroidissement');
assert.notDeepEqual(ids({ cpu: 'AMD Ryzen 5 7600', ram: [{ speed: 6000, configured: 4800 }], need: 'ping' }), ids({ cpu: 'AMD Ryzen 5 7600', need: 'stream obs' }), 'plan différent selon la demande');
console.log('personal plan ok');
{
  const { biosBrand, BIOS_PATHS } = await import('../src/core/oc.js');
  assert.equal(biosBrand('MSI MAG B650 TOMAHAWK WIFI'), 'msi'); assert.equal(biosBrand('ROG STRIX B550-F'), 'asus'); assert.equal(biosBrand('B650 AORUS ELITE'), 'gigabyte'); assert.equal(biosBrand('B760M Steel Legend'), 'asrock'); assert.equal(biosBrand('HP 8A0F'), null);
  for (const b of Object.values(BIOS_PATHS)) for (const p of Object.values(b.tasks)) assert.ok(p.length >= 2);
  console.log('simulateur BIOS ok');
}
